//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpscaylVideo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpscaylVideo.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Common_Auto {
            get {
                return ResourceManager.GetString("Common_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to png.
        /// </summary>
        public static string Common_png {
            get {
                return ResourceManager.GetString("Common_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Common_Videos {
            get {
                return ResourceManager.GetString("Common_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available: {{OriginalFile}}, {{OriginalExtension}}, {{Now &quot;yyyy-MM-dd&quot;&lt;--optional}}.
        /// </summary>
        public static string ConfigPageView_AvailableTemplateVars {
            get {
                return ResourceManager.GetString("ConfigPageView_AvailableTemplateVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use {{Now &quot;format&quot;}} for custom date/time, e.g. {{Now &apos;yyyyMMdd_HHmmss&apos;}}.
        /// </summary>
        public static string ConfigPageView_CustomDateTime {
            get {
                return ResourceManager.GetString("ConfigPageView_CustomDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Output Path:.
        /// </summary>
        public static string ConfigPageView_DefaultOutputPath {
            get {
                return ResourceManager.GetString("ConfigPageView_DefaultOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default: {{OriginalFile}}-upscaled{{OriginalExtension}}.
        /// </summary>
        public static string ConfigPageView_DefaultTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_DefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMpeg Binaries Path:.
        /// </summary>
        public static string ConfigPageView_FFmpegBinariesPath {
            get {
                return ResourceManager.GetString("ConfigPageView_FFmpegBinariesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFMpeg Jpeg Quality.
        /// </summary>
        public static string ConfigPageView_FFMpegJpegQuality {
            get {
                return ResourceManager.GetString("ConfigPageView_FFMpegJpegQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for frame extraction (1-31 - Lower is better).
        /// </summary>
        public static string ConfigPageView_FFMpegJpegQualityHelp {
            get {
                return ResourceManager.GetString("ConfigPageView_FFMpegJpegQualityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank to output to source folder..
        /// </summary>
        public static string ConfigPageView_LeaveBlank {
            get {
                return ResourceManager.GetString("ConfigPageView_LeaveBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Output File Template:.
        /// </summary>
        public static string ConfigPageView_OutputFileNameTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_OutputFileNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default template.
        /// </summary>
        public static string ConfigPageView_ResetToDefaultTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_ResetToDefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paths.
        /// </summary>
        public static string ConfigPageView_Tab_Paths {
            get {
                return ResourceManager.GetString("ConfigPageView_Tab_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Working Folder:.
        /// </summary>
        public static string ConfigPageView_TemporaryWorkingFolder {
            get {
                return ResourceManager.GetString("ConfigPageView_TemporaryWorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscayl Path:.
        /// </summary>
        public static string ConfigPageView_UpscaylPath {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscayl Threads (-j):.
        /// </summary>
        public static string ConfigPageView_UpscaylThreads {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thread count for load/proc/save (default=1:2:2). Examples: 1:2:2 or 1:2,2,2:2 for multi-GPU.
        /// </summary>
        public static string ConfigPageView_UpscaylThreadsHelp {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreadsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format. Use load:proc:save, e.g. 1:2:2 or multi-GPU like 1:2,2,2:2.
        /// </summary>
        public static string ConfigPageView_UpscaylThreadsInvalid {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreadsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string Error_Prefix {
            get {
                return ResourceManager.GetString("Error_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string MainPageView_AddToQueue {
            get {
                return ResourceManager.GetString("MainPageView_AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MainPageView_Cancel {
            get {
                return ResourceManager.GetString("MainPageView_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string MainPageView_CheckUpdates {
            get {
                return ResourceManager.GetString("MainPageView_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codec.
        /// </summary>
        public static string MainPageView_Codec {
            get {
                return ResourceManager.GetString("MainPageView_Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop 4:3 to 16:9.
        /// </summary>
        public static string MainPageView_CropToWidescreen {
            get {
                return ResourceManager.GetString("MainPageView_CropToWidescreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Vertical Offset.
        /// </summary>
        public static string MainPageView_CropVerticalOffset {
            get {
                return ResourceManager.GetString("MainPageView_CropVerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5 = center (default), 0 = crop bottom only, 1 = crop top only.
        /// </summary>
        public static string MainPageView_CropVerticalOffsetTooltip {
            get {
                return ResourceManager.GetString("MainPageView_CropVerticalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete working folder when completed?.
        /// </summary>
        public static string MainPageView_DeleteWorkingFolderWhenCompleted {
            get {
                return ResourceManager.GetString("MainPageView_DeleteWorkingFolderWhenCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string MainPageView_Duration {
            get {
                return ResourceManager.GetString("MainPageView_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forced.
        /// </summary>
        public static string MainPageView_Forced {
            get {
                return ResourceManager.GetString("MainPageView_Forced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Count:.
        /// </summary>
        public static string MainPageView_FrameCount {
            get {
                return ResourceManager.GetString("MainPageView_FrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate:.
        /// </summary>
        public static string MainPageView_Framerate {
            get {
                return ResourceManager.GetString("MainPageView_Framerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gpu #(Blank for auto or comma separated for multiple).
        /// </summary>
        public static string MainPageView_GpuNumberList {
            get {
                return ResourceManager.GetString("MainPageView_GpuNumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image-based subtitles detected. MP4/M4V cannot carry them; output will switch to MKV during merge. You can turn off &quot;Preserve subtitles and attachments&quot; to keep MP4/M4V..
        /// </summary>
        public static string MainPageView_ImageBasedSubsDetected {
            get {
                return ResourceManager.GetString("MainPageView_ImageBasedSubsDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Format.
        /// </summary>
        public static string MainPageView_ImageFormat {
            get {
                return ResourceManager.GetString("MainPageView_ImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Scale ({0}x).
        /// </summary>
        public static string MainPageView_ImageScale {
            get {
                return ResourceManager.GetString("MainPageView_ImageScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number string.
        /// </summary>
        public static string MainPageView_InvalidNumberString {
            get {
                return ResourceManager.GetString("MainPageView_InvalidNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MainPageView_Language {
            get {
                return ResourceManager.GetString("MainPageView_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string MainPageView_Model {
            get {
                return ResourceManager.GetString("MainPageView_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        public static string MainPageView_NewJob {
            get {
                return ResourceManager.GetString("MainPageView_NewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Interpolation (Same as source).
        /// </summary>
        public static string MainPageView_NoInterpolation {
            get {
                return ResourceManager.GetString("MainPageView_NoInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Loaded.
        /// </summary>
        public static string MainPageView_NotLoaded {
            get {
                return ResourceManager.GetString("MainPageView_NotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Dimension:.
        /// </summary>
        public static string MainPageView_OriginalDimension {
            get {
                return ResourceManager.GetString("MainPageView_OriginalDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output container changed to MKV to preserve image-based subtitles..
        /// </summary>
        public static string MainPageView_OutputContainerChangedToMKV {
            get {
                return ResourceManager.GetString("MainPageView_OutputContainerChangedToMKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Path.
        /// </summary>
        public static string MainPageView_OutputPath {
            get {
                return ResourceManager.GetString("MainPageView_OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve subtitles and attachments.
        /// </summary>
        public static string MainPageView_PreserveSubsAttachments {
            get {
                return ResourceManager.GetString("MainPageView_PreserveSubsAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string MainPageView_Preview {
            get {
                return ResourceManager.GetString("MainPageView_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string MainPageView_Queue {
            get {
                return ResourceManager.GetString("MainPageView_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Multiple.
        /// </summary>
        public static string MainPageView_QueueMultiple {
            get {
                return ResourceManager.GetString("MainPageView_QueueMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaled Dimension:.
        /// </summary>
        public static string MainPageView_ScaledDimension {
            get {
                return ResourceManager.GetString("MainPageView_ScaledDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output file.
        /// </summary>
        public static string MainPageView_SelectOutputFile {
            get {
                return ResourceManager.GetString("MainPageView_SelectOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output path.
        /// </summary>
        public static string MainPageView_SelectOutputPath {
            get {
                return ResourceManager.GetString("MainPageView_SelectOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select video file.
        /// </summary>
        public static string MainPageView_SelectVideoFile {
            get {
                return ResourceManager.GetString("MainPageView_SelectVideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select video files.
        /// </summary>
        public static string MainPageView_SelectVideoFiles {
            get {
                return ResourceManager.GetString("MainPageView_SelectVideoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainPageView_Settings {
            get {
                return ResourceManager.GetString("MainPageView_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string MainPageView_Start {
            get {
                return ResourceManager.GetString("MainPageView_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Tracks.
        /// </summary>
        public static string MainPageView_SubtitleTracks {
            get {
                return ResourceManager.GetString("MainPageView_SubtitleTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Size (31 = Auto).
        /// </summary>
        public static string MainPageView_TileSize {
            get {
                return ResourceManager.GetString("MainPageView_TileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Size ({0}).
        /// </summary>
        public static string MainPageView_TileSizeFormat {
            get {
                return ResourceManager.GetString("MainPageView_TileSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the number of frame to process at a time. Since there is currently a memory leak in Upscayl&apos;s Cli process, a high number may use up system memory..
        /// </summary>
        public static string MainPageView_UpscaleChunkSizeTooltip {
            get {
                return ResourceManager.GetString("MainPageView_UpscaleChunkSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscayl Batch Size.
        /// </summary>
        public static string MainPageView_UpscaylBatchSize {
            get {
                return ResourceManager.GetString("MainPageView_UpscaylBatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video File.
        /// </summary>
        public static string MainPageView_VideoFile {
            get {
                return ResourceManager.GetString("MainPageView_VideoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Folder.
        /// </summary>
        public static string MainPageView_WorkingFolder {
            get {
                return ResourceManager.GetString("MainPageView_WorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating….
        /// </summary>
        public static string MainWindow_Calculating {
            get {
                return ResourceManager.GetString("MainWindow_Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk Size.
        /// </summary>
        public static string MainWindow_ChunkSize {
            get {
                return ResourceManager.GetString("MainWindow_ChunkSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Working Folder?.
        /// </summary>
        public static string MainWindow_DeleteWorkingFolder {
            get {
                return ResourceManager.GetString("MainWindow_DeleteWorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed.
        /// </summary>
        public static string MainWindow_Detailed {
            get {
                return ResourceManager.GetString("MainWindow_Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed:.
        /// </summary>
        public static string MainWindow_Elapsed {
            get {
                return ResourceManager.GetString("MainWindow_Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETA:.
        /// </summary>
        public static string MainWindow_ETA {
            get {
                return ResourceManager.GetString("MainWindow_ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frames:.
        /// </summary>
        public static string MainWindow_Frames {
            get {
                return ResourceManager.GetString("MainWindow_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Update.
        /// </summary>
        public static string MainWindow_GetUpdate {
            get {
                return ResourceManager.GetString("MainWindow_GetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU.
        /// </summary>
        public static string MainWindow_Gpu {
            get {
                return ResourceManager.GetString("MainWindow_Gpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Format.
        /// </summary>
        public static string MainWindow_ImageFormat {
            get {
                return ResourceManager.GetString("MainWindow_ImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input:.
        /// </summary>
        public static string MainWindow_Input {
            get {
                return ResourceManager.GetString("MainWindow_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model:.
        /// </summary>
        public static string MainWindow_Model {
            get {
                return ResourceManager.GetString("MainWindow_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output:.
        /// </summary>
        public static string MainWindow_Output {
            get {
                return ResourceManager.GetString("MainWindow_Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Progress:.
        /// </summary>
        public static string MainWindow_OverallProgress {
            get {
                return ResourceManager.GetString("MainWindow_OverallProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale:.
        /// </summary>
        public static string MainWindow_Scale {
            get {
                return ResourceManager.GetString("MainWindow_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: {0}.
        /// </summary>
        public static string MainWindow_StatusFormat {
            get {
                return ResourceManager.GetString("MainWindow_StatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Size.
        /// </summary>
        public static string MainWindow_TileSize {
            get {
                return ResourceManager.GetString("MainWindow_TileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Frames:.
        /// </summary>
        public static string MainWindow_TotalFrames {
            get {
                return ResourceManager.GetString("MainWindow_TotalFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscale Progress:.
        /// </summary>
        public static string MainWindow_UpscaleProgress {
            get {
                return ResourceManager.GetString("MainWindow_UpscaleProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After: {0}.
        /// </summary>
        public static string PreviewPage_AfterFileFormat {
            get {
                return ResourceManager.GetString("PreviewPage_AfterFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Refresh.
        /// </summary>
        public static string PreviewPage_AutoRefresh {
            get {
                return ResourceManager.GetString("PreviewPage_AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Refresh ({0}s).
        /// </summary>
        public static string PreviewPage_AutoRefreshFormat {
            get {
                return ResourceManager.GetString("PreviewPage_AutoRefreshFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before: {0}.
        /// </summary>
        public static string PreviewPage_BeforeFileFormat {
            get {
                return ResourceManager.GetString("PreviewPage_BeforeFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom refresh interval in seconds.
        /// </summary>
        public static string PreviewPage_CustomInterval_Tooltip {
            get {
                return ResourceManager.GetString("PreviewPage_CustomInterval_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame {0} of {1}.
        /// </summary>
        public static string PreviewPage_FrameCount {
            get {
                return ResourceManager.GetString("PreviewPage_FrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame {0} of {1} - Drag to navigate through frames.
        /// </summary>
        public static string PreviewPage_FrameSlider_Tooltip {
            get {
                return ResourceManager.GetString("PreviewPage_FrameSlider_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Interval.
        /// </summary>
        public static string PreviewPage_RefreshInterval {
            get {
                return ResourceManager.GetString("PreviewPage_RefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 seconds.
        /// </summary>
        public static string PreviewPage_RefreshInterval_10s {
            get {
                return ResourceManager.GetString("PreviewPage_RefreshInterval_10s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 seconds.
        /// </summary>
        public static string PreviewPage_RefreshInterval_15s {
            get {
                return ResourceManager.GetString("PreviewPage_RefreshInterval_15s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 seconds.
        /// </summary>
        public static string PreviewPage_RefreshInterval_30s {
            get {
                return ResourceManager.GetString("PreviewPage_RefreshInterval_30s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 seconds.
        /// </summary>
        public static string PreviewPage_RefreshInterval_5s {
            get {
                return ResourceManager.GetString("PreviewPage_RefreshInterval_5s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 seconds.
        /// </summary>
        public static string PreviewPage_RefreshInterval_60s {
            get {
                return ResourceManager.GetString("PreviewPage_RefreshInterval_60s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string PreviewPage_RefreshInterval_Custom {
            get {
                return ResourceManager.GetString("PreviewPage_RefreshInterval_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewPage_Title {
            get {
                return ResourceManager.GetString("PreviewPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Frame.
        /// </summary>
        public static string PreviewPage_Tooltip_NextFrame {
            get {
                return ResourceManager.GetString("PreviewPage_Tooltip_NextFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Frame.
        /// </summary>
        public static string PreviewPage_Tooltip_PreviousFrame {
            get {
                return ResourceManager.GetString("PreviewPage_Tooltip_PreviousFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string QueuePageView_Actions {
            get {
                return ResourceManager.GetString("QueuePageView_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string QueuePageView_Back {
            get {
                return ResourceManager.GetString("QueuePageView_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue.
        /// </summary>
        public static string QueuePageView_ClearQueue {
            get {
                return ResourceManager.GetString("QueuePageView_ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        public static string QueuePageView_ElapsedTime {
            get {
                return ResourceManager.GetString("QueuePageView_ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string QueuePageView_Model {
            get {
                return ResourceManager.GetString("QueuePageView_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        public static string QueuePageView_OutputFile {
            get {
                return ResourceManager.GetString("QueuePageView_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string QueuePageView_Remove {
            get {
                return ResourceManager.GetString("QueuePageView_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string QueuePageView_Scale {
            get {
                return ResourceManager.GetString("QueuePageView_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string QueuePageView_Status {
            get {
                return ResourceManager.GetString("QueuePageView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Path.
        /// </summary>
        public static string QueuePageView_VideoPath {
            get {
                return ResourceManager.GetString("QueuePageView_VideoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        public static string Status_CleaningUp {
            get {
                return ResourceManager.GetString("Status_CleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup failed: {0}.
        /// </summary>
        public static string Status_CleanupFailed {
            get {
                return ResourceManager.GetString("Status_CleanupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting audio....
        /// </summary>
        public static string Status_ExtractingAudio {
            get {
                return ResourceManager.GetString("Status_ExtractingAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting frames....
        /// </summary>
        public static string Status_ExtractingFrames {
            get {
                return ResourceManager.GetString("Status_ExtractingFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting chapter metadata....
        /// </summary>
        public static string Status_ExtractingMetadata {
            get {
                return ResourceManager.GetString("Status_ExtractingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input video or working folder missing..
        /// </summary>
        public static string Status_InputMissing {
            get {
                return ResourceManager.GetString("Status_InputMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job cancelled..
        /// </summary>
        public static string Status_JobCancelled {
            get {
                return ResourceManager.GetString("Status_JobCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job completed..
        /// </summary>
        public static string Status_JobCompleted {
            get {
                return ResourceManager.GetString("Status_JobCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging video and audio....
        /// </summary>
        public static string Status_Merging {
            get {
                return ResourceManager.GetString("Status_Merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file path is empty..
        /// </summary>
        public static string Status_OutputPathEmpty {
            get {
                return ResourceManager.GetString("Status_OutputPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string Status_Queued {
            get {
                return ResourceManager.GetString("Status_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Status_Running {
            get {
                return ResourceManager.GetString("Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source video folder not found..
        /// </summary>
        public static string Status_SourceFolderNotFound {
            get {
                return ResourceManager.GetString("Status_SourceFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscaling cancelled or failed..
        /// </summary>
        public static string Status_UpscalingCancelledOrFailed {
            get {
                return ResourceManager.GetString("Status_UpscalingCancelledOrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscaling frames....
        /// </summary>
        public static string Status_UpscalingFrames {
            get {
                return ResourceManager.GetString("Status_UpscalingFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscayl binary not found..
        /// </summary>
        public static string Status_UpscaylBinaryNotFound {
            get {
                return ResourceManager.GetString("Status_UpscaylBinaryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscayl models folder not found..
        /// </summary>
        public static string Status_UpscaylModelsFolderNotFound {
            get {
                return ResourceManager.GetString("Status_UpscaylModelsFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upscayl path not found..
        /// </summary>
        public static string Status_UpscaylPathNotFound {
            get {
                return ResourceManager.GetString("Status_UpscaylPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available: {0}.
        /// </summary>
        public static string Update_Available {
            get {
                return ResourceManager.GetString("Update_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates….
        /// </summary>
        public static string Update_Checking {
            get {
                return ResourceManager.GetString("Update_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed: {0}.
        /// </summary>
        public static string Update_Failed {
            get {
                return ResourceManager.GetString("Update_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No releases found..
        /// </summary>
        public static string Update_NoReleases {
            get {
                return ResourceManager.GetString("Update_NoReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update checks are not configured..
        /// </summary>
        public static string Update_NotConfigured {
            get {
                return ResourceManager.GetString("Update_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re up to date..
        /// </summary>
        public static string Update_UpToDate {
            get {
                return ResourceManager.GetString("Update_UpToDate", resourceCulture);
            }
        }
    }
}
