//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpscaylVideo {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UpscaylVideo.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MainWindow_Input {
            get {
                return ResourceManager.GetString("MainWindow_Input", resourceCulture);
            }
        }
        
        public static string MainWindow_Output {
            get {
                return ResourceManager.GetString("MainWindow_Output", resourceCulture);
            }
        }
        
        public static string MainWindow_Model {
            get {
                return ResourceManager.GetString("MainWindow_Model", resourceCulture);
            }
        }
        
        public static string MainWindow_Scale {
            get {
                return ResourceManager.GetString("MainWindow_Scale", resourceCulture);
            }
        }
        
        public static string MainWindow_Frames {
            get {
                return ResourceManager.GetString("MainWindow_Frames", resourceCulture);
            }
        }
        
        public static string MainWindow_TotalFrames {
            get {
                return ResourceManager.GetString("MainWindow_TotalFrames", resourceCulture);
            }
        }
        
        public static string MainWindow_ETA {
            get {
                return ResourceManager.GetString("MainWindow_ETA", resourceCulture);
            }
        }
        
        public static string MainWindow_Elapsed {
            get {
                return ResourceManager.GetString("MainWindow_Elapsed", resourceCulture);
            }
        }
        
        public static string MainWindow_UpscaleProgress {
            get {
                return ResourceManager.GetString("MainWindow_UpscaleProgress", resourceCulture);
            }
        }
        
        public static string MainWindow_OverallProgress {
            get {
                return ResourceManager.GetString("MainWindow_OverallProgress", resourceCulture);
            }
        }
        
        public static string MainWindow_ChunkSize {
            get {
                return ResourceManager.GetString("MainWindow_ChunkSize", resourceCulture);
            }
        }
        
        public static string MainWindow_Gpu {
            get {
                return ResourceManager.GetString("MainWindow_Gpu", resourceCulture);
            }
        }
        
        public static string MainWindow_ImageFormat {
            get {
                return ResourceManager.GetString("MainWindow_ImageFormat", resourceCulture);
            }
        }
        
        public static string MainWindow_TileSize {
            get {
                return ResourceManager.GetString("MainWindow_TileSize", resourceCulture);
            }
        }
        
        public static string MainWindow_DeleteWorkingFolder {
            get {
                return ResourceManager.GetString("MainWindow_DeleteWorkingFolder", resourceCulture);
            }
        }
        
        public static string MainPageView_VideoFile {
            get {
                return ResourceManager.GetString("MainPageView_VideoFile", resourceCulture);
            }
        }
        
        public static string MainPageView_WorkingFolder {
            get {
                return ResourceManager.GetString("MainPageView_WorkingFolder", resourceCulture);
            }
        }
        
        public static string MainPageView_OutputPath {
            get {
                return ResourceManager.GetString("MainPageView_OutputPath", resourceCulture);
            }
        }
        
        public static string MainPageView_ImageScale {
            get {
                return ResourceManager.GetString("MainPageView_ImageScale", resourceCulture);
            }
        }
        
        public static string MainPageView_Model {
            get {
                return ResourceManager.GetString("MainPageView_Model", resourceCulture);
            }
        }
        
        public static string MainPageView_UpscaleChunkSize {
            get {
                return ResourceManager.GetString("MainPageView_UpscaleChunkSize", resourceCulture);
            }
        }
        
        public static string MainPageView_UpscaleChunkSizeTooltip {
            get {
                return ResourceManager.GetString("MainPageView_UpscaleChunkSizeTooltip", resourceCulture);
            }
        }
        
        public static string MainPageView_GpuNumberList {
            get {
                return ResourceManager.GetString("MainPageView_GpuNumberList", resourceCulture);
            }
        }
        
        public static string MainPageView_DeleteWorkingFolderWhenCompleted {
            get {
                return ResourceManager.GetString("MainPageView_DeleteWorkingFolderWhenCompleted", resourceCulture);
            }
        }
        
        public static string MainPageView_FrameCount {
            get {
                return ResourceManager.GetString("MainPageView_FrameCount", resourceCulture);
            }
        }
        
        public static string MainPageView_OriginalDimension {
            get {
                return ResourceManager.GetString("MainPageView_OriginalDimension", resourceCulture);
            }
        }
        
        public static string MainPageView_ScaledDimension {
            get {
                return ResourceManager.GetString("MainPageView_ScaledDimension", resourceCulture);
            }
        }
        
        public static string MainPageView_Duration {
            get {
                return ResourceManager.GetString("MainPageView_Duration", resourceCulture);
            }
        }
        
        public static string MainPageView_NotLoaded {
            get {
                return ResourceManager.GetString("MainPageView_NotLoaded", resourceCulture);
            }
        }
        
        public static string MainPageView_Framerate {
            get {
                return ResourceManager.GetString("MainPageView_Framerate", resourceCulture);
            }
        }
        
        public static string MainPageView_ImageFormat {
            get {
                return ResourceManager.GetString("MainPageView_ImageFormat", resourceCulture);
            }
        }
        
        public static string MainPageView_TileSize {
            get {
                return ResourceManager.GetString("MainPageView_TileSize", resourceCulture);
            }
        }
        
        public static string MainPageView_TileSizeFormat {
            get {
                return ResourceManager.GetString("MainPageView_TileSizeFormat", resourceCulture);
            }
        }
        
        public static string ConfigPageView_UpscaylPath {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylPath", resourceCulture);
            }
        }
        
        public static string ConfigPageView_FFmpegBinariesPath {
            get {
                return ResourceManager.GetString("ConfigPageView_FFmpegBinariesPath", resourceCulture);
            }
        }
        
        public static string ConfigPageView_TemporaryWorkingFolder {
            get {
                return ResourceManager.GetString("ConfigPageView_TemporaryWorkingFolder", resourceCulture);
            }
        }
        
        public static string ConfigPageView_DefaultOutputPath {
            get {
                return ResourceManager.GetString("ConfigPageView_DefaultOutputPath", resourceCulture);
            }
        }
        
        public static string ConfigPageView_OutputFileNameTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_OutputFileNameTemplate", resourceCulture);
            }
        }
        
        public static string ConfigPageView_LeaveBlank {
            get {
                return ResourceManager.GetString("ConfigPageView_LeaveBlank", resourceCulture);
            }
        }
        
        public static string ConfigPageView_DefaultTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_DefaultTemplate", resourceCulture);
            }
        }
        
        public static string ConfigPageView_AvailableTemplateVars {
            get {
                return ResourceManager.GetString("ConfigPageView_AvailableTemplateVars", resourceCulture);
            }
        }
        
        public static string ConfigPageView_CustomDateTime {
            get {
                return ResourceManager.GetString("ConfigPageView_CustomDateTime", resourceCulture);
            }
        }
        
        public static string ConfigPageView_ResetToDefaultTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_ResetToDefaultTemplate", resourceCulture);
            }
        }
        
        public static string QueuePageView_Back {
            get {
                return ResourceManager.GetString("QueuePageView_Back", resourceCulture);
            }
        }
        
        public static string QueuePageView_ClearQueue {
            get {
                return ResourceManager.GetString("QueuePageView_ClearQueue", resourceCulture);
            }
        }
        
        public static string QueuePageView_Status {
            get {
                return ResourceManager.GetString("QueuePageView_Status", resourceCulture);
            }
        }
        
        public static string QueuePageView_VideoPath {
            get {
                return ResourceManager.GetString("QueuePageView_VideoPath", resourceCulture);
            }
        }
        
        public static string QueuePageView_Model {
            get {
                return ResourceManager.GetString("QueuePageView_Model", resourceCulture);
            }
        }
        
        public static string QueuePageView_Scale {
            get {
                return ResourceManager.GetString("QueuePageView_Scale", resourceCulture);
            }
        }
        
        public static string QueuePageView_OutputFile {
            get {
                return ResourceManager.GetString("QueuePageView_OutputFile", resourceCulture);
            }
        }
        
        public static string QueuePageView_Actions {
            get {
                return ResourceManager.GetString("QueuePageView_Actions", resourceCulture);
            }
        }
        
        public static string QueuePageView_Remove {
            get {
                return ResourceManager.GetString("QueuePageView_Remove", resourceCulture);
            }
        }
        
        public static string QueuePageView_ElapsedTime {
            get {
                return ResourceManager.GetString("QueuePageView_ElapsedTime", resourceCulture);
            }
        }
        
        public static string Status_Queued {
            get {
                return ResourceManager.GetString("Status_Queued", resourceCulture);
            }
        }
        
        public static string Status_Running {
            get {
                return ResourceManager.GetString("Status_Running", resourceCulture);
            }
        }
        
        public static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        public static string ConfigPageView_UpscaylThreads {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreads", resourceCulture);
            }
        }
        
        public static string ConfigPageView_UpscaylThreadsHelp {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreadsHelp", resourceCulture);
            }
        }
        
        public static string ConfigPageView_UpscaylThreadsInvalid {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreadsInvalid", resourceCulture);
            }
        }
    }
}
