//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpscaylVideo {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UpscaylVideo.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string MainWindow_Input {
            get {
                return ResourceManager.GetString("MainWindow_Input", resourceCulture);
            }
        }
        
        public static string MainWindow_Output {
            get {
                return ResourceManager.GetString("MainWindow_Output", resourceCulture);
            }
        }
        
        public static string MainWindow_Model {
            get {
                return ResourceManager.GetString("MainWindow_Model", resourceCulture);
            }
        }
        
        public static string MainWindow_Scale {
            get {
                return ResourceManager.GetString("MainWindow_Scale", resourceCulture);
            }
        }
        
        public static string MainWindow_Frames {
            get {
                return ResourceManager.GetString("MainWindow_Frames", resourceCulture);
            }
        }
        
        public static string MainWindow_TotalFrames {
            get {
                return ResourceManager.GetString("MainWindow_TotalFrames", resourceCulture);
            }
        }
        
        public static string MainWindow_ETA {
            get {
                return ResourceManager.GetString("MainWindow_ETA", resourceCulture);
            }
        }
        
        public static string MainWindow_Elapsed {
            get {
                return ResourceManager.GetString("MainWindow_Elapsed", resourceCulture);
            }
        }
        
        public static string MainWindow_UpscaleProgress {
            get {
                return ResourceManager.GetString("MainWindow_UpscaleProgress", resourceCulture);
            }
        }
        
        public static string MainWindow_OverallProgress {
            get {
                return ResourceManager.GetString("MainWindow_OverallProgress", resourceCulture);
            }
        }
        
        public static string MainWindow_ChunkSize {
            get {
                return ResourceManager.GetString("MainWindow_ChunkSize", resourceCulture);
            }
        }
        
        public static string MainWindow_Gpu {
            get {
                return ResourceManager.GetString("MainWindow_Gpu", resourceCulture);
            }
        }
        
        public static string MainWindow_ImageFormat {
            get {
                return ResourceManager.GetString("MainWindow_ImageFormat", resourceCulture);
            }
        }
        
        public static string MainWindow_TileSize {
            get {
                return ResourceManager.GetString("MainWindow_TileSize", resourceCulture);
            }
        }
        
        public static string MainWindow_DeleteWorkingFolder {
            get {
                return ResourceManager.GetString("MainWindow_DeleteWorkingFolder", resourceCulture);
            }
        }
        
        public static string MainPageView_VideoFile {
            get {
                return ResourceManager.GetString("MainPageView_VideoFile", resourceCulture);
            }
        }
        
        public static string MainPageView_WorkingFolder {
            get {
                return ResourceManager.GetString("MainPageView_WorkingFolder", resourceCulture);
            }
        }
        
        public static string MainPageView_OutputPath {
            get {
                return ResourceManager.GetString("MainPageView_OutputPath", resourceCulture);
            }
        }
        
        public static string MainPageView_ImageScale {
            get {
                return ResourceManager.GetString("MainPageView_ImageScale", resourceCulture);
            }
        }
        
        public static string MainPageView_Model {
            get {
                return ResourceManager.GetString("MainPageView_Model", resourceCulture);
            }
        }
        
        public static string MainPageView_UpscaylBatchSize {
            get {
                return ResourceManager.GetString("MainPageView_UpscaylBatchSize", resourceCulture);
            }
        }
        
        public static string MainPageView_UpscaleChunkSizeTooltip {
            get {
                return ResourceManager.GetString("MainPageView_UpscaleChunkSizeTooltip", resourceCulture);
            }
        }
        
        public static string MainPageView_GpuNumberList {
            get {
                return ResourceManager.GetString("MainPageView_GpuNumberList", resourceCulture);
            }
        }
        
        public static string MainPageView_DeleteWorkingFolderWhenCompleted {
            get {
                return ResourceManager.GetString("MainPageView_DeleteWorkingFolderWhenCompleted", resourceCulture);
            }
        }
        
        public static string MainPageView_FrameCount {
            get {
                return ResourceManager.GetString("MainPageView_FrameCount", resourceCulture);
            }
        }
        
        public static string MainPageView_OriginalDimension {
            get {
                return ResourceManager.GetString("MainPageView_OriginalDimension", resourceCulture);
            }
        }
        
        public static string MainPageView_ScaledDimension {
            get {
                return ResourceManager.GetString("MainPageView_ScaledDimension", resourceCulture);
            }
        }
        
        public static string MainPageView_Duration {
            get {
                return ResourceManager.GetString("MainPageView_Duration", resourceCulture);
            }
        }
        
        public static string MainPageView_NotLoaded {
            get {
                return ResourceManager.GetString("MainPageView_NotLoaded", resourceCulture);
            }
        }
        
        public static string MainPageView_Framerate {
            get {
                return ResourceManager.GetString("MainPageView_Framerate", resourceCulture);
            }
        }
        
        public static string MainPageView_ImageFormat {
            get {
                return ResourceManager.GetString("MainPageView_ImageFormat", resourceCulture);
            }
        }
        
        public static string MainPageView_TileSize {
            get {
                return ResourceManager.GetString("MainPageView_TileSize", resourceCulture);
            }
        }
        
        public static string MainPageView_TileSizeFormat {
            get {
                return ResourceManager.GetString("MainPageView_TileSizeFormat", resourceCulture);
            }
        }

        public static string MainPageView_PreserveSubsAttachments {
            get {
                return ResourceManager.GetString("MainPageView_PreserveSubsAttachments", resourceCulture);
            }
        }

        public static string MainPageView_SubtitleTracks {
            get {
                return ResourceManager.GetString("MainPageView_SubtitleTracks", resourceCulture);
            }
        }

        public static string MainPageView_Language {
            get {
                return ResourceManager.GetString("MainPageView_Language", resourceCulture);
            }
        }

        public static string MainPageView_Codec {
            get {
                return ResourceManager.GetString("MainPageView_Codec", resourceCulture);
            }
        }

        public static string MainPageView_Forced {
            get {
                return ResourceManager.GetString("MainPageView_Forced", resourceCulture);
            }
        }

        public static string MainPageView_OutputContainerChangedToMKV {
            get {
                return ResourceManager.GetString("MainPageView_OutputContainerChangedToMKV", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image-based subtitles detected. MP4/M4V cannot carry them; output will switch to MKV during merge. You can turn off “Preserve subtitles and attachments” to keep MP4/M4V.. 
        /// </summary>
        public static string MainPageView_ImageBasedSubsDetected {
            get {
                return ResourceManager.GetString("MainPageView_ImageBasedSubsDetected", resourceCulture);
            }
        }
        
        public static string ConfigPageView_UpscaylPath {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylPath", resourceCulture);
            }
        }
        
        public static string ConfigPageView_FFmpegBinariesPath {
            get {
                return ResourceManager.GetString("ConfigPageView_FFmpegBinariesPath", resourceCulture);
            }
        }
        
        public static string ConfigPageView_TemporaryWorkingFolder {
            get {
                return ResourceManager.GetString("ConfigPageView_TemporaryWorkingFolder", resourceCulture);
            }
        }
        
        public static string ConfigPageView_DefaultOutputPath {
            get {
                return ResourceManager.GetString("ConfigPageView_DefaultOutputPath", resourceCulture);
            }
        }
        
        public static string ConfigPageView_OutputFileNameTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_OutputFileNameTemplate", resourceCulture);
            }
        }
        
        public static string ConfigPageView_LeaveBlank {
            get {
                return ResourceManager.GetString("ConfigPageView_LeaveBlank", resourceCulture);
            }
        }
        
        public static string ConfigPageView_DefaultTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_DefaultTemplate", resourceCulture);
            }
        }
        
        public static string ConfigPageView_AvailableTemplateVars {
            get {
                return ResourceManager.GetString("ConfigPageView_AvailableTemplateVars", resourceCulture);
            }
        }
        
        public static string ConfigPageView_CustomDateTime {
            get {
                return ResourceManager.GetString("ConfigPageView_CustomDateTime", resourceCulture);
            }
        }
        
        public static string ConfigPageView_ResetToDefaultTemplate {
            get {
                return ResourceManager.GetString("ConfigPageView_ResetToDefaultTemplate", resourceCulture);
            }
        }
        
        public static string QueuePageView_Back {
            get {
                return ResourceManager.GetString("QueuePageView_Back", resourceCulture);
            }
        }
        
        public static string QueuePageView_ClearQueue {
            get {
                return ResourceManager.GetString("QueuePageView_ClearQueue", resourceCulture);
            }
        }
        
        public static string QueuePageView_Status {
            get {
                return ResourceManager.GetString("QueuePageView_Status", resourceCulture);
            }
        }
        
        public static string QueuePageView_VideoPath {
            get {
                return ResourceManager.GetString("QueuePageView_VideoPath", resourceCulture);
            }
        }
        
        public static string QueuePageView_Model {
            get {
                return ResourceManager.GetString("QueuePageView_Model", resourceCulture);
            }
        }
        
        public static string QueuePageView_Scale {
            get {
                return ResourceManager.GetString("QueuePageView_Scale", resourceCulture);
            }
        }
        
        public static string QueuePageView_OutputFile {
            get {
                return ResourceManager.GetString("QueuePageView_OutputFile", resourceCulture);
            }
        }
        
        public static string QueuePageView_Actions {
            get {
                return ResourceManager.GetString("QueuePageView_Actions", resourceCulture);
            }
        }
        
        public static string QueuePageView_Remove {
            get {
                return ResourceManager.GetString("QueuePageView_Remove", resourceCulture);
            }
        }
        
        public static string QueuePageView_ElapsedTime {
            get {
                return ResourceManager.GetString("QueuePageView_ElapsedTime", resourceCulture);
            }
        }
        
        public static string Status_Queued {
            get {
                return ResourceManager.GetString("Status_Queued", resourceCulture);
            }
        }
        
        public static string Status_Running {
            get {
                return ResourceManager.GetString("Status_Running", resourceCulture);
            }
        }
        
        public static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        public static string ConfigPageView_UpscaylThreads {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreads", resourceCulture);
            }
        }
        
        public static string ConfigPageView_UpscaylThreadsHelp {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreadsHelp", resourceCulture);
            }
        }
        
        public static string ConfigPageView_UpscaylThreadsInvalid {
            get {
                return ResourceManager.GetString("ConfigPageView_UpscaylThreadsInvalid", resourceCulture);
            }
        }
        
        public static string MainPageView_CheckUpdates {
            get {
                return ResourceManager.GetString("MainPageView_CheckUpdates", resourceCulture);
            }
        }
        
        public static string MainWindow_GetUpdate {
            get {
                return ResourceManager.GetString("MainWindow_GetUpdate", resourceCulture);
            }
        }
        
        public static string Update_Checking {
            get {
                return ResourceManager.GetString("Update_Checking", resourceCulture);
            }
        }
        
        public static string Update_NotConfigured {
            get {
                return ResourceManager.GetString("Update_NotConfigured", resourceCulture);
            }
        }
        
        public static string Update_NoReleases {
            get {
                return ResourceManager.GetString("Update_NoReleases", resourceCulture);
            }
        }
        
        public static string Update_Available {
            get {
                return ResourceManager.GetString("Update_Available", resourceCulture);
            }
        }
        
        public static string Update_UpToDate {
            get {
                return ResourceManager.GetString("Update_UpToDate", resourceCulture);
            }
        }
        
        public static string Update_Failed {
            get {
                return ResourceManager.GetString("Update_Failed", resourceCulture);
            }
        }
        
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        public static string Common_Auto {
            get {
                return ResourceManager.GetString("Common_Auto", resourceCulture);
            }
        }
        
        public static string Common_Videos {
            get {
                return ResourceManager.GetString("Common_Videos", resourceCulture);
            }
        }
        
        public static string Common_png {
            get {
                return ResourceManager.GetString("Common_png", resourceCulture);
            }
        }
        
        public static string MainWindow_StatusFormat {
            get {
                return ResourceManager.GetString("MainWindow_StatusFormat", resourceCulture);
            }
        }
        
        public static string MainWindow_Detailed {
            get {
                return ResourceManager.GetString("MainWindow_Detailed", resourceCulture);
            }
        }
        
        public static string MainWindow_Calculating {
            get {
                return ResourceManager.GetString("MainWindow_Calculating", resourceCulture);
            }
        }
        
        public static string ConfigPageView_Tab_Paths {
            get {
                return ResourceManager.GetString("ConfigPageView_Tab_Paths", resourceCulture);
            }
        }
        
        public static string ConfigPageView_FFMpegJpegQuality {
            get {
                return ResourceManager.GetString("ConfigPageView_FFMpegJpegQuality", resourceCulture);
            }
        }
        
        public static string ConfigPageView_FFMpegJpegQualityHelp {
            get {
                return ResourceManager.GetString("ConfigPageView_FFMpegJpegQualityHelp", resourceCulture);
            }
        }
        
        public static string MainPageView_NewJob {
            get {
                return ResourceManager.GetString("MainPageView_NewJob", resourceCulture);
            }
        }
        
        public static string MainPageView_QueueMultiple {
            get {
                return ResourceManager.GetString("MainPageView_QueueMultiple", resourceCulture);
            }
        }
        
        public static string MainPageView_Start {
            get {
                return ResourceManager.GetString("MainPageView_Start", resourceCulture);
            }
        }
        
        public static string MainPageView_AddToQueue {
            get {
                return ResourceManager.GetString("MainPageView_AddToQueue", resourceCulture);
            }
        }
        
        public static string MainPageView_Cancel {
            get {
                return ResourceManager.GetString("MainPageView_Cancel", resourceCulture);
            }
        }
        
        public static string MainPageView_Queue {
            get {
                return ResourceManager.GetString("MainPageView_Queue", resourceCulture);
            }
        }
        
        public static string MainPageView_Settings {
            get {
                return ResourceManager.GetString("MainPageView_Settings", resourceCulture);
            }
        }
        
        public static string MainPageView_Preview {
            get {
                return ResourceManager.GetString("MainPageView_Preview", resourceCulture);
            }
        }
        
        public static string MainPageView_SelectVideoFile {
            get {
                return ResourceManager.GetString("MainPageView_SelectVideoFile", resourceCulture);
            }
        }
        
        public static string MainPageView_SelectVideoFiles {
            get {
                return ResourceManager.GetString("MainPageView_SelectVideoFiles", resourceCulture);
            }
        }
        
        public static string MainPageView_SelectOutputPath {
            get {
                return ResourceManager.GetString("MainPageView_SelectOutputPath", resourceCulture);
            }
        }
        
        public static string MainPageView_SelectOutputFile {
            get {
                return ResourceManager.GetString("MainPageView_SelectOutputFile", resourceCulture);
            }
        }
        
        public static string MainPageView_InvalidNumberString {
            get {
                return ResourceManager.GetString("MainPageView_InvalidNumberString", resourceCulture);
            }
        }
        
        public static string MainPageView_NoInterpolation {
            get {
                return ResourceManager.GetString("MainPageView_NoInterpolation", resourceCulture);
            }
        }
        
        public static string Status_InputMissing {
            get {
                return ResourceManager.GetString("Status_InputMissing", resourceCulture);
            }
        }
        
        public static string Status_UpscaylPathNotFound {
            get {
                return ResourceManager.GetString("Status_UpscaylPathNotFound", resourceCulture);
            }
        }
        
        public static string Status_UpscaylBinaryNotFound {
            get {
                return ResourceManager.GetString("Status_UpscaylBinaryNotFound", resourceCulture);
            }
        }
        
        public static string Status_UpscaylModelsFolderNotFound {
            get {
                return ResourceManager.GetString("Status_UpscaylModelsFolderNotFound", resourceCulture);
            }
        }
        
        public static string Status_SourceFolderNotFound {
            get {
                return ResourceManager.GetString("Status_SourceFolderNotFound", resourceCulture);
            }
        }
        
        public static string Status_OutputPathEmpty {
            get {
                return ResourceManager.GetString("Status_OutputPathEmpty", resourceCulture);
            }
        }
        
        public static string Status_ExtractingAudio {
            get {
                return ResourceManager.GetString("Status_ExtractingAudio", resourceCulture);
            }
        }
        
        public static string Status_ExtractingMetadata {
            get {
                return ResourceManager.GetString("Status_ExtractingMetadata", resourceCulture);
            }
        }
        
        public static string Status_ExtractingFrames {
            get {
                return ResourceManager.GetString("Status_ExtractingFrames", resourceCulture);
            }
        }
        
        public static string Status_UpscalingFrames {
            get {
                return ResourceManager.GetString("Status_UpscalingFrames", resourceCulture);
            }
        }
        
        public static string Status_UpscalingCancelledOrFailed {
            get {
                return ResourceManager.GetString("Status_UpscalingCancelledOrFailed", resourceCulture);
            }
        }
        
        public static string Status_JobCancelled {
            get {
                return ResourceManager.GetString("Status_JobCancelled", resourceCulture);
            }
        }
        
        public static string Status_Merging {
            get {
                return ResourceManager.GetString("Status_Merging", resourceCulture);
            }
        }
        
        public static string Status_JobCompleted {
            get {
                return ResourceManager.GetString("Status_JobCompleted", resourceCulture);
            }
        }
        
        public static string Status_CleaningUp {
            get {
                return ResourceManager.GetString("Status_CleaningUp", resourceCulture);
            }
        }
        
        public static string Status_CleanupFailed {
            get {
                return ResourceManager.GetString("Status_CleanupFailed", resourceCulture);
            }
        }
        
        public static string Error_Prefix {
            get {
                return ResourceManager.GetString("Error_Prefix", resourceCulture);
            }
        }
        
        public static string PreviewPage_Title {
            get {
                return ResourceManager.GetString("PreviewPage_Title", resourceCulture);
            }
        }
        
        public static string PreviewPage_AutoRefresh {
            get {
                return ResourceManager.GetString("PreviewPage_AutoRefresh", resourceCulture);
            }
        }
        
        public static string PreviewPage_AutoRefreshFormat {
            get {
                return ResourceManager.GetString("PreviewPage_AutoRefreshFormat", resourceCulture);
            }
        }
        
        public static string PreviewPage_BeforeFileFormat {
            get {
                return ResourceManager.GetString("PreviewPage_BeforeFileFormat", resourceCulture);
            }
        }
        
        public static string PreviewPage_AfterFileFormat {
            get {
                return ResourceManager.GetString("PreviewPage_AfterFileFormat", resourceCulture);
            }
        }

        public static string PreviewPage_Tooltip_PreviousFrame {
            get {
                return ResourceManager.GetString("PreviewPage_Tooltip_PreviousFrame", resourceCulture);
            }
        }

        public static string PreviewPage_Tooltip_NextFrame {
            get {
                return ResourceManager.GetString("PreviewPage_Tooltip_NextFrame", resourceCulture);
            }
        }
    }
}
